sudo: required
services:
  - docker

before_install:
  - docker build -t wp-client:prod .

script:
  docker run -e CI=true -d -p 80:80 wp-client:prod

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "wp-client"
  env: "wp-client-eb"
  bucket_name: "elasticbeanstalk-eu-central-1-447041063491"
  bucket_path: "wp-client"
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  on:
    branch: master

after_deploy:
  - echo "Applcation Deployed!"