sudo: required
services:
  - docker

before_install:
  - docker build -t wp-client .

script:
  - docker run -e CI=true wp-client

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "wp-client"
  env: "wp-client-env"
  bucket_name: "elasticbeanstalk-eu-central-1-447041063491"
  bucket_path: "wp-client"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master